apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: monapp
spec:
  template:
    metadata:
      labels:
        app: myapp
        version: "1.0"
    spec:
      containers:
      - name: nginx
        image: nginx:1.18  
  replicas: 3
  selector:
    matchLabels:
      app: myapp
    matchExpressions:
      - key: version
        operator: In
        values: ["1.0", "2.0"]
