apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: busy
        image: busybox
        command: ["sleep", "3600"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: stress-container
        image: ubuntu
        command: ["/bin/bash", "-c", "apt-get update && apt-get install -y stress && stress --cpu 2 --timeout 600"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1